### PR TITLE
Albin/gig 783 migrate documentation

### PR DESCRIPTION
**Pull request by AlbinLindskog**

### CODE REVIEW

**Comment by EmberCraze** [comment]
# We separate the iteration into two, so we can insert our own divider in the middle (unclear what this means)

The Gigapay API is organized around REST Our API (should be The Gigapay API is organized around REST. Our API)

The Gigapay API Supports IP-whitelisting. When requesting API-keys, let us know which IP:s you would like to restrict access from (This sounds like we are blacklisting instead of whitelisting)

retrieve an Integration shows webhooks instead of integrations

This endpoint replaces a webhooks.

This endpoint deletes a webhooks.

This endpoint creates a webhooks.

Either email or cellphone_number is required.( one of them has to be requierd right )

This endpoint resend an invitation.(maybe resends?)

invoice 	25 	Relational Filter. (unclear what relational filter means)

Note that you can not delete a payout belonging to a paid Invoice. (strings such as this should be in bold so the developer is reads it)

This endpoint resends a notification.(what kind of notification? payout employee etc)

Maybe should have a type column instead of combining type and description in the same field

Why use price? is it because it also tells you the price of the transaction and does the rest for you in a single call?

some fields such as full_salary_specification are mentioned later in the code but you have to go way back to read an explanation

This endpoint retrieves a payout. (should be: This endpoint retrieves information regarding a payout?)

The Webhook object(should be the invoice object)

Maybe don't use gigatron in the webhooks link. It was hard to discern the difference between gigapay and gigatron

Maybe change the order of info so that the objects come after the authentication. It would speedup the development. And then when a developer needs help he/she will look at the section related to their problem

**Comment by gustav** [comment]
Is it possible to delete an Integration and all it's related objects or are there limitations to this similar to when deleting an Employee with Payouts?

**Comment by gustav** [comment]
Maybe we should move to default True for full_salary_specfication btw

**Comment by gustav** [comment]
Made my suggested changes here: https://github.com/gigapay/slate/pull/2

**Comment by Jokezor** [comment]
Great work :)

I found nothing that stuck out.

**Pull request merged**
